spring:
  application:
    name: msc-db-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.85.200:8848
  datasource:
    druid:
      url: jdbc:mysql://120.79.85.200:3306/msc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.miracle.msc.db.provider.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 4000


management:
  endpoints:
    web:
      exposure:
        include: "*"
