server:
  port: 3000

spring:
  application:
    name: activemq-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.85.200:8848
  activemq:
    broker-url: tcp://120.79.85.200:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true  #false:Queue，true:Topic

management:
  endpoints:
    web:
      exposure:
        include: "*"

myTopic: msc-activemq-topic